version: '3'
services:
  kafka:
    image: apache/kafka:3.7.0
    ports:
      - "9092:9092"
    volumes:
      - kafka-data:/var/lib/kafka
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: codeflix
      MYSQL_USER: codeflix
      MYSQL_PASSWORD: codeflix
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
#  connect:
#    image: quay.io/debezium/connect:2.5
#    ports:
#      - "8083:8083"
#    environment:
#      BOOTSTRAP_SERVERS: kafka:9092
##      BOOTSTRAP_SERVERS: "host.docker.internal:9092"
#      GROUP_ID: 1  # Identify connectors of the same cluster
#      CONFIG_STORAGE_TOPIC: my_connect_configs
#      OFFSET_STORAGE_TOPIC: my_connect_offsets
#      STATUS_STORAGE_TOPIC: my_connect_statuses
#    depends_on:
#      - kafka
#      - mysql
volumes:
  kafka-data:
  mysql-data:
